name: CI
on: [push]
jobs:
  CI-Bun:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "0.8.1"
      - run: bun install
      - run: bun format:check
      - run: bun run build
  CI-Node:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install --install-strategy=linked
      - run: npm run format:check
      - run: npm run build
